### ISSUE TITLE
While Running "sample_trainer.py"

### ISSUE THREAD

**Issue by jageshmaharjan** [SEERNET/DeepSpeaker#6]
On the line:
 history = model.fit_generator(
        train_gen, steps_per_epoch=data_generator.train_spe, epochs=epochs,
        validation_data=validation_gen, workers=workers, validation_steps=data_generator.validation_spe,
        callbacks=[checkpointer, tensorboard]
    )

of “sample_trainer.py” file. Encounter the following error:

data_generator_task
    generator_output = next(self._generator)
TypeError: 'ThreadSafeIter' object is not an iterator

and 

fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by venkatesh-1729** [comment]
@jageshmaharjan If you create TfRecords for train, validation, and test successfully you should be able to train models using the following command.
```
usage: sample_trainer.py [-h] [--batch_size BATCH_SIZE]
                         [--model_type {dnn,rnn,cnn}] [--epochs EPOCHS]
                         [--num_threads NUM_THREADS]
                         train_tfrecord_file validation_tfrecord_file
                         test_tfrecord_file
```
Example:
```
python deepspeaker/trainers/sample_trainer.py train.tfrecords validation.tfrecords test.tfrecords --batch_size 64 --model_type dnn --epochs 50
```
If you are still facing an issue please provide stacktrace.

**Comment by jageshmaharjan** [comment]
I was able to create "train.tfrecords", "validation.tfrecords" and "test.tfrecords" in "tfr_dir" directory, However, when i run "sample_trainer.py", i encounter with the error.
The below is the full stack trace:

/home/jugs/anaconda3/envs/tensorflow/bin/python "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/trainers/sample_trainer.py" "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/data_generators/tfr_dir/1508312907/train.tfrecords" "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/data_generators/tfr_dir/1508312907/validation.tfrecords" "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/data_generators/tfr_dir/1508312907/test.tfrecords"
Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 4096)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               2097664   
_________________________________________________________________
batch_normalization_1 (Batch (None, 512)               2048      
_________________________________________________________________
activation_1 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
batch_normalization_2 (Batch (None, 512)               2048      
_________________________________________________________________
activation_2 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 512)               262656    
_________________________________________________________________
batch_normalization_3 (Batch (None, 512)               2048      
_________________________________________________________________
activation_3 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 50)                25650     
=================================================================
Total params: 2,654,770
Trainable params: 2,651,698
Non-trainable params: 3,072
_________________________________________________________________
Epoch 1/100
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
TypeError: 'ThreadSafeIter' object is not an iterator

Traceback (most recent call last):
  File "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/trainers/sample_trainer.py", line 121, in <module>
    runs_path=runs_dir
  File "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/trainers/sample_trainer.py", line 58, in sample_trainer
    callbacks=[checkpointer, tensorboard]
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/models.py", line 1121, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by venkatesh-1729** [comment]
@jageshmaharjan I didn't verify if this code is compatible with python 3.x but this patch may solve the problem for you.

Change `ThreadSafeIter` class in `deepspeaker/utils/generic_utils.py` file to this:
```python
class ThreadSafeIter:
    """Takes an iterator/generator and makes it thread-safe by
    serializing call to the `next` method of given iterator/generator.
    """

    def __init__(self, it):
        self.it = it
        self.lock = threading.Lock()

    def __iter__(self):
        return self

    # python 2.x compatible
    def next(self):
        with self.lock:
            return self.it.next()

    # python 3.x compatible
    def __next__(self):
        with self.lock:
            return self.it.next()
```

**Comment by jageshmaharjan** [comment]
@venkatesh-1729 ,  Didn't work. Still the same Stack trace.

**Comment by venkatesh-1729** [comment]
```python
    # python 3.x compatible
    def __next__(self):
        with self.lock:
            return self.it.next()
```
Try using this instead of the above snippet:
```python
    # python 3.x compatible
    def __next__(self):
        with self.lock:
            return self.it.__next__()
```

**Comment by jageshmaharjan** [comment]
Still the same. :(

**Comment by sushant-hiray** [comment]
Hi @jageshmaharjan thanks for reporting the issue. After updating the code, can you please run 
`python setup.py install` and then try running your script again.

The snippet added by @venkatesh-1729 should fix the issue.

**Comment by jageshmaharjan** [comment]
Hi @sushant-hiray , I ran the "setup.py" file. But Still, with the same issue.

(tensorflow) jugs@jugs:~/Documents/SR Work/DeepSpeaker-dev-SEERNET$ python setup.py install
running install
Command ['apt-get', 'update'] failed: exit code: 100
running build
running build_py
running egg_info
writing DeepSpeaker.egg-info/PKG-INFO
writing dependency_links to DeepSpeaker.egg-info/dependency_links.txt
writing requirements to DeepSpeaker.egg-info/requires.txt
writing top-level names to DeepSpeaker.egg-info/top_level.txt
reading manifest file 'DeepSpeaker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'deepspeaker/resources/sample_audio_files/sample.wav'
writing manifest file 'DeepSpeaker.egg-info/SOURCES.txt'
running install_lib
running install_egg_info
removing '/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/DeepSpeaker-0.1.1-py3.6.egg-info' (and everything under it)
Copying DeepSpeaker.egg-info to /home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/DeepSpeaker-0.1.1-py3.6.egg-info
running install_scripts

**Comment by sushant-hiray** [comment]
This should be fine. The `apt-get` commands are for ci installation. We are just logging the error. Your package has been installed correctly. 
Here is the relevant line:
```
Copying DeepSpeaker.egg-info to /home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/DeepSpeaker-0.1.1-py3.6.egg-info
```

**Comment by jageshmaharjan** [comment]
I mean, "python setup.py install" ran successfully. However, when I run the "sample_trainer.py", I still encounter the previous StackTrace.

_________________________________________________________________
Epoch 1/100
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/utils/generic_utils.py", line 52, in __next__
    return self.it.__next__()
StopIteration

Traceback (most recent call last):
  File "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/trainers/sample_trainer.py", line 121, in <module>
    runs_path=runs_dir
  File "/home/jugs/Documents/SR Work/DeepSpeaker-dev-SEERNET/deepspeaker/trainers/sample_trainer.py", line 58, in sample_trainer
    callbacks=[checkpointer, tensorboard]
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/models.py", line 1121, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/jugs/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by sushant-hiray** [comment]
In line 52: can you add `self.it.__next__()` as @venkatesh-1729 mentioned in [this comment](https://github.com/SEERNET/DeepSpeaker/issues/6#issuecomment-337644063)

**Comment by jageshmaharjan** [comment]
@sushant-hiray , its actually "self.it.__next__()" [compatible for python 3.x]. 
Just in this git its shown as bold due to double underscore(__)

**Comment by jageshmaharjan** [comment]
I don't know if this is really working, or just not raising a "StopIteration" Error.
I add this lines on "~/utils/generic_utils.py" file

`    def __next__(self):
        try:
            with self.lock:
                return self.it.__next__()
        except StopIteration:
            pass`

**Comment by venkatesh-1729** [comment]
@jageshmaharjan now the code is compatible with Python 3.x. Try running it after cloning and installing latest dev.

**Comment by jageshmaharjan** [comment]
@venkatesh-1729 , Perfect.
Working well. Thanks a lot.
